language: python
before_script:
  - sleep 1
python:
  - "3.6"
# command to install dependencies
install:
  # Travis will automatically do git clone
  - pip install -r requirements_dev.txt
  - pip install pylint
  - pip install -e .
# command to run tests
script:
#- pylint *.py
- pytest
